name: Create Release on Merge to Master

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and release project 1
      working-directory: ./dart-client/java-ui-client
      run: |
        mvn clean package
        mvn deploy

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token, um das Release zu veröffentlichen
      
        
